name: jellyfin-gradle-pr

on:
  pull_request

concurrency:
  group: jellyfin-gradle-${{ github.ref }}
  cancel-in-progress: true

permissions:
  pull-requests: read
  contents: read

jobs:
  jellyfin-gradle-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            jellyfin-gradle:
              - '.support/jellyfin-gradle/**'

      - name: Ensure jellyfin-gradle binary is regenerated
        if: steps.changes.outputs.jellyfin-gradle == 'true'
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1
          if ! git diff --name-only HEAD^ HEAD | grep -q ".support/.m2/com/eygraber/jellyfin/gradle/jellyfin-gradle/maven-metadata.xml"; then
            echo 'Run .scripts/publish_included_builds to regenerate the jellyfin-gradle binary'
            exit 1
          elif ! git diff --name-only HEAD^ HEAD | grep -q ".support/.m2/jellyfin-gradle/jellyfin-gradle.gradle.plugin/maven-metadata.xml"; then
            echo 'Run .scripts/publish_included_builds to regenerate the jellyfin-gradle binary'
            exit 1
          fi

      - name: Setup for building
        if: steps.changes.outputs.jellyfin-gradle == 'true'
        uses: ./.github/actions/build-setup

      - name: Run ktlint
        if: steps.changes.outputs.jellyfin-gradle == 'true'
        run: ./format --no-format --check-support

      - name: Run detekt
        if: steps.changes.outputs.jellyfin-gradle == 'true'
        run: ./gradlew -p .support/jellyfin-gradle detekt

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx16g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=1024m"
