name: template-gradle-pr

on:
  pull_request

concurrency:
  group: template-gradle-${{ github.ref }}
  cancel-in-progress: true

permissions:
  pull-requests: read
  contents: read

jobs:
  template-gradle-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            template-gradle:
              - '.support/template-gradle/**'

      - name: Ensure template-gradle binary is regenerated
        if: steps.changes.outputs.template-gradle == 'true'
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1
          if ! git diff --name-only HEAD^ HEAD | grep -q ".support/.m2/template/gradle/template-gradle/maven-metadata.xml"; then
            echo 'Run .scripts/publish_included_builds to regenerate the template-gradle binary'
            exit 1
          elif ! git diff --name-only HEAD^ HEAD | grep -q ".support/.m2/template-gradle/template-gradle.gradle.plugin/maven-metadata.xml"; then
            echo 'Run .scripts/publish_included_builds to regenerate the template-gradle binary'
            exit 1
          fi

      - name: Setup for building
        if: steps.changes.outputs.template-gradle == 'true'
        uses: ./.github/actions/build-setup

      - name: Run ktlint
        if: steps.changes.outputs.template-gradle == 'true'
        run: ./format --no-format --check-support

      - name: Run detekt
        if: steps.changes.outputs.template-gradle == 'true'
        run: ./gradlew -p .support/template-gradle detekt

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx16g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=1024m"
